/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ConsoleK9r4vxm2qh7nRouteImport } from './routes/console-k9r4vxm2qh7n'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarotIndexRouteImport } from './routes/tarot.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as TarotCardKeyRouteImport } from './routes/tarot.$cardKey'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiWhopWebhookRouteImport } from './routes/api/whop/webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiOpsIpChallengeRouteImport } from './routes/api/ops/ip-challenge'
import { Route as ApiFlittCallbackRouteImport } from './routes/api/flitt/callback'
import { Route as ApiCreemWebhookRouteImport } from './routes/api/creem/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleK9r4vxm2qh7nRoute = ConsoleK9r4vxm2qh7nRouteImport.update({
  id: '/console-k9r4vxm2qh7n',
  path: '/console-k9r4vxm2qh7n',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotIndexRoute = TarotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TarotRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const TarotCardKeyRoute = TarotCardKeyRouteImport.update({
  id: '/$cardKey',
  path: '/$cardKey',
  getParentRoute: () => TarotRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhopWebhookRoute = ApiWhopWebhookRouteImport.update({
  id: '/api/whop/webhook',
  path: '/api/whop/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsIpChallengeRoute = ApiOpsIpChallengeRouteImport.update({
  id: '/api/ops/ip-challenge',
  path: '/api/ops/ip-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlittCallbackRoute = ApiFlittCallbackRouteImport.update({
  id: '/api/flitt/callback',
  path: '/api/flitt/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreemWebhookRoute = ApiCreemWebhookRouteImport.update({
  id: '/api/creem/webhook',
  path: '/api/creem/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/console-k9r4vxm2qh7n': typeof ConsoleK9r4vxm2qh7nRoute
  '/feedback': typeof FeedbackRoute
  '/guidelines': typeof GuidelinesRoute
  '/guides': typeof GuidesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tarot': typeof TarotRouteWithChildren
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tarot/$cardKey': typeof TarotCardKeyRoute
  '/guides/': typeof GuidesIndexRoute
  '/tarot/': typeof TarotIndexRoute
  '/api/creem/webhook': typeof ApiCreemWebhookRoute
  '/api/flitt/callback': typeof ApiFlittCallbackRoute
  '/api/ops/ip-challenge': typeof ApiOpsIpChallengeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whop/webhook': typeof ApiWhopWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/console-k9r4vxm2qh7n': typeof ConsoleK9r4vxm2qh7nRoute
  '/feedback': typeof FeedbackRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tarot/$cardKey': typeof TarotCardKeyRoute
  '/guides': typeof GuidesIndexRoute
  '/tarot': typeof TarotIndexRoute
  '/api/creem/webhook': typeof ApiCreemWebhookRoute
  '/api/flitt/callback': typeof ApiFlittCallbackRoute
  '/api/ops/ip-challenge': typeof ApiOpsIpChallengeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whop/webhook': typeof ApiWhopWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/console-k9r4vxm2qh7n': typeof ConsoleK9r4vxm2qh7nRoute
  '/feedback': typeof FeedbackRoute
  '/guidelines': typeof GuidelinesRoute
  '/guides': typeof GuidesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tarot': typeof TarotRouteWithChildren
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tarot/$cardKey': typeof TarotCardKeyRoute
  '/guides/': typeof GuidesIndexRoute
  '/tarot/': typeof TarotIndexRoute
  '/api/creem/webhook': typeof ApiCreemWebhookRoute
  '/api/flitt/callback': typeof ApiFlittCallbackRoute
  '/api/ops/ip-challenge': typeof ApiOpsIpChallengeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whop/webhook': typeof ApiWhopWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ads.txt'
    | '/console-k9r4vxm2qh7n'
    | '/feedback'
    | '/guidelines'
    | '/guides'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/tarot'
    | '/terms'
    | '/auth/callback'
    | '/guides/$slug'
    | '/tarot/$cardKey'
    | '/guides/'
    | '/tarot/'
    | '/api/creem/webhook'
    | '/api/flitt/callback'
    | '/api/ops/ip-challenge'
    | '/api/stripe/webhook'
    | '/api/whop/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ads.txt'
    | '/console-k9r4vxm2qh7n'
    | '/feedback'
    | '/guidelines'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/auth/callback'
    | '/guides/$slug'
    | '/tarot/$cardKey'
    | '/guides'
    | '/tarot'
    | '/api/creem/webhook'
    | '/api/flitt/callback'
    | '/api/ops/ip-challenge'
    | '/api/stripe/webhook'
    | '/api/whop/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ads.txt'
    | '/console-k9r4vxm2qh7n'
    | '/feedback'
    | '/guidelines'
    | '/guides'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/tarot'
    | '/terms'
    | '/auth/callback'
    | '/guides/$slug'
    | '/tarot/$cardKey'
    | '/guides/'
    | '/tarot/'
    | '/api/creem/webhook'
    | '/api/flitt/callback'
    | '/api/ops/ip-challenge'
    | '/api/stripe/webhook'
    | '/api/whop/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  ConsoleK9r4vxm2qh7nRoute: typeof ConsoleK9r4vxm2qh7nRoute
  FeedbackRoute: typeof FeedbackRoute
  GuidelinesRoute: typeof GuidelinesRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TarotRoute: typeof TarotRouteWithChildren
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiCreemWebhookRoute: typeof ApiCreemWebhookRoute
  ApiFlittCallbackRoute: typeof ApiFlittCallbackRoute
  ApiOpsIpChallengeRoute: typeof ApiOpsIpChallengeRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWhopWebhookRoute: typeof ApiWhopWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console-k9r4vxm2qh7n': {
      id: '/console-k9r4vxm2qh7n'
      path: '/console-k9r4vxm2qh7n'
      fullPath: '/console-k9r4vxm2qh7n'
      preLoaderRoute: typeof ConsoleK9r4vxm2qh7nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/': {
      id: '/tarot/'
      path: '/'
      fullPath: '/tarot/'
      preLoaderRoute: typeof TarotIndexRouteImport
      parentRoute: typeof TarotRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/tarot/$cardKey': {
      id: '/tarot/$cardKey'
      path: '/$cardKey'
      fullPath: '/tarot/$cardKey'
      preLoaderRoute: typeof TarotCardKeyRouteImport
      parentRoute: typeof TarotRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whop/webhook': {
      id: '/api/whop/webhook'
      path: '/api/whop/webhook'
      fullPath: '/api/whop/webhook'
      preLoaderRoute: typeof ApiWhopWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/ip-challenge': {
      id: '/api/ops/ip-challenge'
      path: '/api/ops/ip-challenge'
      fullPath: '/api/ops/ip-challenge'
      preLoaderRoute: typeof ApiOpsIpChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flitt/callback': {
      id: '/api/flitt/callback'
      path: '/api/flitt/callback'
      fullPath: '/api/flitt/callback'
      preLoaderRoute: typeof ApiFlittCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creem/webhook': {
      id: '/api/creem/webhook'
      path: '/api/creem/webhook'
      fullPath: '/api/creem/webhook'
      preLoaderRoute: typeof ApiCreemWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface TarotRouteChildren {
  TarotCardKeyRoute: typeof TarotCardKeyRoute
  TarotIndexRoute: typeof TarotIndexRoute
}

const TarotRouteChildren: TarotRouteChildren = {
  TarotCardKeyRoute: TarotCardKeyRoute,
  TarotIndexRoute: TarotIndexRoute,
}

const TarotRouteWithChildren = TarotRoute._addFileChildren(TarotRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  ConsoleK9r4vxm2qh7nRoute: ConsoleK9r4vxm2qh7nRoute,
  FeedbackRoute: FeedbackRoute,
  GuidelinesRoute: GuidelinesRoute,
  GuidesRoute: GuidesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TarotRoute: TarotRouteWithChildren,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiCreemWebhookRoute: ApiCreemWebhookRoute,
  ApiFlittCallbackRoute: ApiFlittCallbackRoute,
  ApiOpsIpChallengeRoute: ApiOpsIpChallengeRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWhopWebhookRoute: ApiWhopWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
